version: '3'
services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  adminer:
    image: adminer
    ports:
      - 8081:8080
  node-app:
    build: gate-simulator
    image: node:10-alpine
    ports:
      - '9999:9999'