version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: gate-simulator
    image: node:10-alpine
    ports:
      - '9999:9999'